### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by earwig** [earwig/bitshift#1]
## Labor division
- Ben K.
  - Database, semantic analysis
- Severyn
  - Frontend, crawler
- Ben A.
  - Frontend, semantic analysis
### Checklist
- [x] regex searching
- [x] identify language type
- [x] identify types of code (classes, functions, variables)
- [x] code written by author 
- [ ] identifying coding conventions 
- [ ] identifying techniques in code
### Checklist
- [x] base search syntax (for without javascript)
- [x] autocompleting for components of the search (converts to base syntax)
- [x] scroll through results
- [x] show preview of relevant snippet with syntax highlighting
- [ ] ability to take down results
- [x] show cached code
- [ ] projects that a person may have contributed to
- [x] dates of authorship
- [ ] type code licenses
## Crawling
- tree like recursive crawling algorithm for github
- crawl new questions for stackoverflow
- follow correct crawler syntax (robots.txt)
- recrawling github active projects and contributions
- crawl source code, modified, authors, url, project name, filename in project
- 1 thread per site for crawling
- Semantic analysis when crawling (using tags)
### Checklist
- [x] github
- [ ] stackoverflow
- [x] bitbucket
- [ ] ~~gittorius~~
- [ ] ~~local installs of vcs software~~
- [ ] ~~launchpad~~
- [ ] ~~google code~~
## Parser
- Code language without file extensions will be harder to detect
- Will use pygments, and will attempt to parse with given language
- Tree of language organized by similarity
  - Will attempt to parse with lowest nodes first, then will go up the language tree to parse
### Checklist
- [x] identity code language
- [x] parse code with ASTs
- [x] integrate with backend and search
## Backend
- Constructing a complex sql query
- Small test database dump in git
### Tasks
- [ ] advertising job openings
