### ISSUE TITLE
Add crawler

### ISSUE THREAD

**Issue by sevko** [earwig/bitshift#2]
## Tasks
- [x] Add parent crawler module.
- [x] Add all subsidiary crawler modules.
- [x] Complete crawler package.
## Crawlers
- [x] GitHub
- [x] Bitbucket
- [ ] ~~Gitorious~~
- [ ] ~~local installs of git repositories~~
- [ ] ~~Mercurial repositories~~
- [ ] ~~Subversion repositories~~
- [ ] ~~Programmer's blogs~~

**Comment by sevko** [comment]
Closing, as no more Codelet harvesting capacity is currently necessary.
